"""
This module provides loop generator layers, i.e., layers that take a
link field :math:`U` and compute a set of gauge equivariant loops.

All layers inherit from ``AbstractLoopGenerator`` and provide the class property
``nfeatures_out``. This allows to access the number of generated loops programatically::

    features_in = PositiveOrientationPlaquetteGenerator.nfeatures_out
    generator = PositiveOrientationPlaquetteGenerator()
    ...
"""

from abc import ABCMeta, abstractmethod
import torch
from typing import Dict, Any
from ...base.paths import PathBuffer

class AbstractLoopGenerator(metaclass=ABCMeta):
    """Abstract base class for loop generators.

    All loop generators must implement the nfeatures_out property.
    """
    @classmethod
    @property
    def nfeatures_out(cls: type) -> int:
        """Get the number of output features for this loop generator.

        Returns:
            The number of output features (loops) generated by this class.
        """
        return cls.property_nfeatures_out

    @property
    @abstractmethod
    def property_nfeatures_out(self) -> int:
        """Abstract property that concrete subclasses must implement.

        Returns:
            The number of output features.
        """
        pass


class PolyakovLoopGenerator(torch.nn.Module, AbstractLoopGenerator):
    r"""
    Generates the Polyakov loops

    .. math::
        P_\mu(x) = \prod\limits_{k=0}^{L_\mu} U_\mu(x + k\mu)

    for :math:`\mu = 0,1,2,3`.

    Attributes:
        cache (dict): Cache for storing computed loops.
        disable_cache (bool): Whether to disable caching.
    """

    property_nfeatures_out: int = 4  # XXX This expects 4D fields.

    def __init__(self, disable_cache: bool = True) -> None:
        """Initialize the PolyakovLoopGenerator.

        Args:
            disable_cache: Whether to disable caching of computed loops.
        """
        super(PolyakovLoopGenerator, self).__init__()
        self.cache: Dict[int, torch.Tensor] = {}
        self.disable_cache = disable_cache

    def clear_cache(self) -> None:
        """Clear the cache of computed loops."""
        self.cache = {}

    def forward(self, U: torch.Tensor) -> torch.Tensor:
        """Compute the Polyakov loops.

        Args:
            U: The gauge field tensor.

        Returns:
            Stacked tensor of Polyakov loops for each direction.
        """
        if id(U) in self.cache:
            loops = self.cache[id(U)]
        else:
            paths = [[(mu, 1) for _ in L_mu] for mu, L_mu in enumerate(U[0].shape)]
            loops = torch.stack([PathBuffer(U, path).gauge_transport_matrix for path in paths])
            if not self.disable_cache:
                self.cache[id(U)] = loops
        return loops


class PositiveOrientationPlaquetteGenerator(torch.nn.Module, AbstractLoopGenerator):
    r"""
    Generates the positively oriented plaquettes, i.e.,

    .. math::
        P_{\mu\nu}(x) = U_\mu(x) U_\nu(x+\mu) U_\mu^\dagger(x+\nu) U_\nu^\dagger(x)

    Attributes:
        cache (dict): Cache for storing computed plaquettes.
        disable_cache (bool): Whether to disable caching.
    """

    property_nfeatures_out: int = 6

    def __init__(self, disable_cache: bool = True) -> None:
        """Initialize the PositiveOrientationPlaquetteGenerator.

        Args:
            disable_cache: Whether to disable caching of computed plaquettes.
        """
        super(PositiveOrientationPlaquetteGenerator, self).__init__()

        self.cache: Dict[int, torch.Tensor] = {}
        self.disable_cache = disable_cache

    def clear_cache(self) -> None:
        """Clear the cache of computed plaquettes."""
        self.cache = {}

    def forward(self, U: torch.Tensor) -> torch.Tensor:
        """Compute the positively oriented plaquettes.

        Args:
            U: The gauge field tensor.

        Returns:
            Stacked tensor of positively oriented plaquettes.
        """
        if id(U) in self.cache:
            loops = self.cache[id(U)]
        else:

            paths = [[(mu, 1), (nu, 1), (mu, -1), (nu, -1)]
                     for mu in range(4) for nu in range(mu)]
            # Remove the empty path generated above.
            paths = [pi for pi in paths if len(pi)]

            loops = torch.stack([PathBuffer(U, path).gauge_transport_matrix for path in paths])
            if not self.disable_cache:
                self.cache[id(U)] = loops
        return loops
